# Generated by Django 4.1.5 on 2023-01-04 11:49

from django.db import migrations, models
import django.db.models.deletion
import model.shortenermodel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgermodel', '0002_alter_ledger_amount_alter_ledger_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=model.shortenermodel.models.generate_short_id, editable=False, max_length=7, unique=True)),
                ('expired_dt', models.DateTimeField(default=model.shortenermodel.models.default_time)),
                ('ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledgermodel.ledger')),
            ],
        ),
    ]
