# Generated by Django 4.1.5 on 2023-01-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenermodel', '0002_rename_ledger_id_shortener_ledger'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shortener',
            table='short_url',
        ),
    ]
