# Generated by Django 4.1.5 on 2023-01-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgermodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
