# Generated by Django 4.1.5 on 2023-01-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgermodel', '0002_alter_ledger_amount_alter_ledger_create_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ledger',
            table='ledger',
        ),
    ]
